import fetch from '@/utils/fetch'

export default {
  // 经营主体分布管理
  enterpriseCount() {
    // return fetch({
    //   url: '/admin/platform/enterpriseCount',
    //   method: 'get'
    // })
    return Promise.resolve({
      "status": 200,
      "msg": "操作成功",
      "data": {
        "enterpriseTypeList": [
          {
            "nodeTypeId": 1,
            "nodeTypeName": "银川市",
            "nodeTypeNo": "1"
          },
          {
            "nodeTypeId": 2,
            "nodeTypeName": "石嘴山市",
            "nodeTypeNo": "2"
          },
          {
            "nodeTypeId": 4,
            "nodeTypeName": "吴忠市",
            "nodeTypeNo": "4"
          },
          {
            "nodeTypeId": 5,
            "nodeTypeName": "固原市",
            "nodeTypeNo": "5"
          },
          {
            "nodeTypeId": 6,
            "nodeTypeName": "中卫市",
            "nodeTypeNo": "6"
          },
          {
            "nodeTypeId": 7,
            "nodeTypeName": "葡萄产业发展局",
            "nodeTypeNo": "7"
          }
        ],
        "enterpriseTypeCount": {
          "1": [
            {
              "enterpriseId": 484,
              "enterpriseNo": "EI2017122300000004",
              "enterpriseName": "润百禾现代农业科技有限公司",
              "address": "宁夏",
              "telephone": "123456789",
              "fax": "123456",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-25 17:59:51",
              "updateTime": 1514343476759,
              "businessTypes": "1,2",
              "enterpriseType": 1,
              "nodeTypeNos": "1,",
              "hasBusiness": 0,
              "recordEnterpriseNo": null,
              "recordEnterpriseName": null,
              "rejectReason": null,
              "confirmTime": "2017-12-27 10:26:45",
              "legalRepresent": "张三",
              "legalId": "123456789123456789",
              "legalType": 1,
              "socialCreditCode": "234234",
              "recordDate": "2017-12-01",
              "issuingDate": "2017-12-26",
              "termOfValidity": "2017-12-19",
              "areaCode": "370102",
              "longitude": 106.310871,
              "latitude": 38.503008,
              "contacts": "李四",
              "cityCode": "370100",
              "confirmUserId": 1,
              "recordUserId": 1
            },
            {
              "enterpriseId": 4,
              "enterpriseNo": "EI2017120700000004",
              "enterpriseName": "银座超市",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740813,
              "businessTypes": "1",
              "enterpriseType": 3,
              "nodeTypeNos": "1,2,4,7",
              "hasBusiness": 0,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:07",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 106.242542,
              "latitude": 38.473305,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            },
            {
              "enterpriseId": 7,
              "enterpriseNo": "EI2017120700000007",
              "enterpriseName": "金鼎配送中心",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740821,
              "businessTypes": "1",
              "enterpriseType": 1,
              "nodeTypeNos": "1,6,",
              "hasBusiness": 1,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:06",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 106.156394,
              "latitude": 38.49604,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            },
            {
              "enterpriseId": 5,
              "enterpriseNo": "EI2017120700000005",
              "enterpriseName": "顺成超市",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740816,
              "businessTypes": "1",
              "enterpriseType": 1,
              "nodeTypeNos": "1,4",
              "hasBusiness": 1,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:08",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 106.340054,
              "latitude": 38.102655,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            }
          ],
          "2": [
            {
              "enterpriseId": 4,
              "enterpriseNo": "EI2017120700000004",
              "enterpriseName": "银座超市",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740813,
              "businessTypes": "1",
              "enterpriseType": 3,
              "nodeTypeNos": "1,2,4,7",
              "hasBusiness": 0,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:07",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 106.373279,
              "latitude": 39.012413,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            },
            {
              "enterpriseId": 10,
              "enterpriseNo": "EI2017120700000000",
              "enterpriseName": "山东省万兴食品有限公司",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740829,
              "businessTypes": "1",
              "enterpriseType": 2,
              "nodeTypeNos": "2,",
              "hasBusiness": 0,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": null,
              "confirmTime": "2017-12-24 18:26:22",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 106.752651,
              "latitude": 39.247574,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            }
          ],
          "4": [
            {
              "enterpriseId": 4,
              "enterpriseNo": "EI2017120700000004",
              "enterpriseName": "银座超市",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740813,
              "businessTypes": "1",
              "enterpriseType": 3,
              "nodeTypeNos": "1,2,4,7",
              "hasBusiness": 0,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:07",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 106.197841,
              "latitude": 37.98253,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            },
            {
              "enterpriseId": 9,
              "enterpriseNo": "EI2017120700000009",
              "enterpriseName": "五福茶叶有限公司",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740827,
              "businessTypes": "1",
              "enterpriseType": 0,
              "nodeTypeNos": "6,4,5",
              "hasBusiness": 1,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:05",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 106.078022,
              "latitude": 38.022298,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            },
            {
              "enterpriseId": 5,
              "enterpriseNo": "EI2017120700000005",
              "enterpriseName": "顺成超市",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740816,
              "businessTypes": "1",
              "enterpriseType": 1,
              "nodeTypeNos": "1,4",
              "hasBusiness": 1,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:08",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 107.407359,
              "latitude": 37.783205,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            },
            {
              "enterpriseId": 6,
              "enterpriseNo": "EI2017120700000006",
              "enterpriseName": "营昊超市",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740818,
              "businessTypes": "1",
              "enterpriseType": 0,
              "nodeTypeNos": "4,",
              "hasBusiness": 0,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:06",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 105.914458,
              "latitude": 36.980575,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            }
          ],
          "5": [
            {
              "enterpriseId": 9,
              "enterpriseNo": "EI2017120700000009",
              "enterpriseName": "五福茶叶有限公司",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740827,
              "businessTypes": "1",
              "enterpriseType": 0,
              "nodeTypeNos": "6,4,5",
              "hasBusiness": 1,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:05",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 106.285241,
              "latitude": 36.004561,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            }
          ],
          "6": [
            {
              "enterpriseId": 7,
              "enterpriseNo": "EI2017120700000007",
              "enterpriseName": "金鼎配送中心",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740821,
              "businessTypes": "1",
              "enterpriseType": 1,
              "nodeTypeNos": "1,6,",
              "hasBusiness": 1,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:06",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 105.189568,
              "latitude": 37.514951,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            },
            {
              "enterpriseId": 9,
              "enterpriseNo": "EI2017120700000009",
              "enterpriseName": "五福茶叶有限公司",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740827,
              "businessTypes": "1",
              "enterpriseType": 0,
              "nodeTypeNos": "6,4,5",
              "hasBusiness": 1,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:05",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 105.190536,
              "latitude": 37.514564,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            },
            {
              "enterpriseId": 13,
              "enterpriseNo": "EI2017120700000012",
              "enterpriseName": "朗野蜂业有限公司",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740837,
              "businessTypes": "1",
              "enterpriseType": 1,
              "nodeTypeNos": "6,",
              "hasBusiness": 0,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:03",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 105.643487,
              "latitude": 36.565033,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            },
            {
              "enterpriseId": 501,
              "enterpriseNo": "EI2017122700000001",
              "enterpriseName": "家乐福连锁超市",
              "address": "家乐福连锁超市",
              "telephone": "18522303663",
              "fax": "01598526230",
              "registeredCapital": null,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-27 15:06:03",
              "updateTime": null,
              "businessTypes": "1,2",
              "enterpriseType": 3,
              "nodeTypeNos": "6,",
              "hasBusiness": null,
              "recordEnterpriseNo": null,
              "recordEnterpriseName": null,
              "rejectReason": null,
              "confirmTime": "2017-12-27 15:07:21",
              "legalRepresent": "沙华",
              "legalId": "110111198911236118",
              "legalType": 1,
              "socialCreditCode": "91430111MA4G16JQ9B",
              "recordDate": "2017-12-27",
              "issuingDate": "2017-09-01",
              "termOfValidity": "2021-12-31",
              "areaCode": "371203",
              "longitude": 105.685285,
              "latitude": 37.491505,
              "contacts": "沙华",
              "cityCode": "371200",
              "confirmUserId": 1,
              "recordUserId": 1
            }
          ],
          "7": [
            {
              "enterpriseId": 4,
              "enterpriseNo": "EI2017120700000004",
              "enterpriseName": "银座超市",
              "address": "测试地址",
              "telephone": "13866666666",
              "fax": "010-88888888",
              "registeredCapital": 0,
              "isDelete": 1,
              "isConfirm": 1,
              "createTime": "2017-12-11 15:52:20",
              "updateTime": 1512978740813,
              "businessTypes": "1",
              "enterpriseType": 3,
              "nodeTypeNos": "1,2,4,7",
              "hasBusiness": 0,
              "recordEnterpriseNo": "string",
              "recordEnterpriseName": "string",
              "rejectReason": "string",
              "confirmTime": "2017-12-27 10:58:07",
              "legalRepresent": "string",
              "legalId": "string",
              "legalType": 1,
              "socialCreditCode": "string",
              "recordDate": "2017-12-07",
              "issuingDate": "2017-12-07",
              "termOfValidity": "2017-12-07",
              "areaCode": "string",
              "longitude": 106.235357,
              "latitude": 38.518322,
              "contacts": "吕金起",
              "cityCode": "string",
              "confirmUserId": 1,
              "recordUserId": 1
            }
          ]
        },
        "enterpriseTotalNum": 9
      },
      "rel": false
    })
  },
  // 设备运行状况
  equipmentRunStatus() {
    return fetch({
      url: '/admin/platform/equipmentRunStatus',
      method: 'get'
    })
  },
  // 上季度追溯数据分析
  getTraceDataAnalysisData() {
    return fetch({
      url: '/admin/platform/lastQuarterTraceDataAnalysis',
      method: 'get'
    })
  },
  // 工作考核分析
  getLastMonthWorkAnalysis() {
    return fetch({
      url: '/admin/platform/lastMonthWorkAnalysis',
      method: 'get'
    })
  },
  // 今日提示
  getTodayStat() {
    return fetch({
      url: '/admin/platform/todayStat',
      method: 'get'
    })
  },
  // 各流通节点考核情况分析
  getNodeTypeExamineAnalysisList() {
    return fetch({
      url: '/admin/platform/getNodeTypeExamineAnalysisList',
      method: 'get'
    })
  },
  // 各流通节点考核情况分析
  getScanCodeCount() {
    return fetch({
      url: '/interfaces-rezen/sanCode/getScanCodeCount',
      method: 'get'
    })
  }
}
