export const GET_MENU_LIST = 'GET_MENU_LIST'
export const GET_CREDIT_RANK_TABLE_DATA = 'GET_CREDIT_RANK_TABLE_DATA'
export const GET_DEVICE_TYPE_TABLE_DATA = 'GET_DEVICE_TYPE_TABLE_DATA'
export const GET_DEVICE_MODEL_TABLE_DATA = 'GET_DEVICE_MODEL_TABLE_DATA'
export const DEVICE_MANAGE_TABLE_DATA = 'DEVICE_MANAGE_TABLE_DATA'
// 门户管理 新闻发布管理
export const GET_INFO_PUBLISH_TABLE_DATA = 'GET_INFO_PUBLISH_TABLE_DATA'
export const GET_NEWS_ENUMS = 'GET_NEWS_ENUMS'
// 门户管理 追溯企业
export const GET_BACK_ENTERPRISE_TABLE_DATA = 'GET_BACK_ENTERPRISE_TABLE_DATA'
// 门户管理 电商链接
export const GET_ECOMMERCE_LINKS_TABLE_DATA = 'GET_ECOMMERCE_LINKS_TABLE_DATA'
export const GET_CIRNODATE_INFO_TABLE_DATE = 'GET_CIRNODATE_INFO_TABLE_DATE'
export const GET_PRO_INFO_TABLE_DATE = 'GET_PRO_INFO_TABLE_DATE'
export const GET_CATEGORY_RANK_TABLE_DATA = 'GET_CATEGORY_RANK_TABLE_DATA'
export const GET_SON_INFO_TABLE_DATE = 'GET_SON_INFO_TABLE_DATE'
export const GET_SCAT_INFO_TABLE_DATE = 'GET_SCAT_INFO_TABLE_DATE'
// 门户管理 公众留言反馈 未处理信息
export const GET_LEAVE_MESSAGE_NOT_DEAL_TABLE_DATA = 'GET_LEAVE_MESSAGE_NOT_DEAL_TABLE_DATA'
// 门户管理 公众留言反馈 已处理信息
export const GET_LEAVE_MESSAGE_HAVE_DEAL_TABLE_DATA = 'GET_LEAVE_MESSAGE_HAVE_DEAL_TABLE_DATA'
// 门户管理 模板管理
export const GET_TEMPLATE_MANAGE_TABLE_DATA = 'GET_TEMPLATE_MANAGE_TABLE_DATA'
// 门户管理 栏目管理
export const GET_CHANNEL_MANAGE_TABLE_DATA = 'GET_CHANNEL_MANAGE_TABLE_DATA'
// 系统设置 设备类别管理
export const GET_EQUIPMENT_TYPE_TABLE_DATA = 'GET_EQUIPMENT_TYPE_TABLE_DATA'
// 系统设置 设备型号管理
export const GET_EQUIPMENT_MODEL_TABLE_DATA = 'GET_EQUIPMENT_MODEL_TABLE_DATA'
// 系统设置 设备监控项管理
export const GET_EQUIPMENT_MONITOR_OPTION_TABLE_DATA = 'GET_EQUIPMENT_MONITOR_OPTION_TABLE_DATA'
// 组织权限管理 用户管理
export const GET_USER_MANAGE_TABLE_DATA = 'GET_USER_MANAGE_TABLE_DATA'
// 组织权限管理 用户管理 部门管理
export const GET_DEPARTMENT_MANAGE_DEPARTMENT_LIST = 'GET_DEPARTMENT_MANAGE_DEPARTMENT_LIST'
export const GET_DEPARTMENT_MANAGE_PARENT_DEPARTMENT = 'GET_DEPARTMENT_MANAGE_PARENT_DEPARTMENT'
// 组织权限管理 角色管理
export const GET_ROLE_MANAGE_TABLE_DATE = 'GET_ROLE_MANAGE_TABLE_DATE'
// 组织权限管理 权限管理
export const GET_PERMISSION_MANAGE_TABLE_DATA = 'GET_PERMISSION_MANAGE_TABLE_DATA'
// 日志管理 用户操作日志
export const GET_USER_OPT_LOG_TABLE_DATA = 'GET_USER_OPT_LOG_TABLE_DATA'
// 日志管理 系统运行日志
export const GET_SYSTEM_RUN_LOG_TABLE_DATA = 'GET_SYSTEM_RUN_LOG_TABLE_DATA'
// 系统内部权限
export const GET_SYSTEM_INNER_PERMISSION_TABLE_DATA = 'GET_SYSTEM_INNER_PERMISSION_TABLE_DATA'
// 菜单管理
export const GET_ALL_MENUS = 'GET_ALL_MENUS'
