export const GET_MENU_LIST = 'GET_MENU_LIST'
export const GET_CREDIT_RANK_TABLE_DATA = 'GET_CREDIT_RANK_TABLE_DATA'
export const GET_REPORT_ANALYSIS_TABLE_DATA = 'GET_REPORT_ANALYSIS_TABLE_DATA'
export const GET_TRACEABILITY_TABLE_DATA = 'GET_TRACEABILITY_TABLE_DATA'
//大数据挖掘展示  --> 价格走势
export const GET_PRICE_TREND_TABLE_DATA = 'GET_PRICE_TREND_TABLE_DATA'
//大数据挖掘展示  --> 价格预测
export const GET_PRICE_FORECAST_TABLE_DATA = 'GET_PRICE_FORECAST_TABLE_DATA'
//大数据挖掘展示  --> 宁夏追溯产品价格比对
export const GET_PRICE_COMPARISON_TABLE_DATA = 'GET_PRICE_COMPARISON_TABLE_DATA'
