export const GET_NODE_RECORD_TABLE_DATA = 'GET_NODE_RECORD_TABLE_DATA'
export const GET_CREDIT_RANK_TABLE_DATA = 'GET_CREDIT_RANK_TABLE_DATA'
export const GET_ENTERPRISE_SUMMARY_TABLE_DATA = 'GET_ENTERPRISE_SUMMARY_TABLE_DATA'
export const GET_ANALYSIS_REPORT_TABLE_DATA = 'GET_ANALYSIS_REPORT_TABLE_DATA'
// 追溯信息管理 --> 追溯链条合成
export const GET_CHAIN_SYNTHESIS_TABLE_DATA = 'GET_CHAIN_SYNTHESIS_TABLE_DATA'
// 追溯信息管理 --> 剔除信息恢复
export const GET_DELETE_RECOVER_TABLE_DATA = 'GET_DELETE_RECOVER_TABLE_DATA'
// 追溯信息管理 --> 剔除信息统计
export const GET_DELETE_STATISTICS_TABLE_DATA = 'GET_DELETE_STATISTICS_TABLE_DATA'
// 追溯管理系统 --> 信息备案管理 --> 管理者备案
export const GET_NODE_RECORD_LIST = 'GET_NODE_RECORD_LIST'
// 追溯管理系统 --> 备案信息统计
export const GET_FILE_STATISTICS_DATA = 'GET_FILE_STATISTICS_DATA'
export const GET_ENTERPRISE_INFO_TABLE_DATA = 'GET_ENTERPRISE_INFO_TABLE_DATA'
export const GET_BUSINESSES_USING_LIST = 'GET_BUSINESSES_USING_LIST'
// 枚举
export const GET_BUSINESS_TYPES = 'GET_BUSINESS_TYPES'
export const GET_ENTERPRISE_TYPES = 'GET_ENTERPRISE_TYPES'
export const GET_IS_CONFIRMS = 'GET_IS_CONFIRMS'
export const GET_IS_DELETES = 'GET_IS_DELETES'
export const GET_LEGAL_TYPES = 'GET_LEGAL_TYPES'
export const GET_NODE_TYPES = 'GET_NODE_TYPES'
export const GET_PROPERTIES = 'GET_PROPERTIES'
export const GET_ADMIN_RECORD_TABLE_DATA = 'GET_ADMIN_RECORD_TABLE_DATA'
export const GET_STORE_RECORD_LIST = 'GET_STORE_RECORD_LIST'
export const GET_RUNNING_REPORT_TABLE_DATA = 'GET_RUNNING_REPORT_TABLE_DATA'
// 系统首页 企业备案统计
export const GET_ENTERPRISE_RECORDS_NUM_COUNT_DATA = 'GET_ENTERPRISE_RECORDS_NUM_COUNT_DATA'
// 系统首页 追溯数据分析
export const GET_TRACE_DATA_ANALYSIS_DATA = 'GET_TRACE_DATA_ANALYSIS_DATA'
// 系统首页 追溯数据数量分析
export const GET_TRACE_DATA_COUNT_ANALYSIS_DATA = 'GET_TRACE_DATA_COUNT_ANALYSIS_DATA'
// 追溯信息查询
export const GET_DATA_TYPES = 'GET_DATA_TYPES'
export const GET_PAGE_DATA = 'GET_PAGE_DATA'
