export const GET_MENU_LIST = 'GET_MENU_LIST'
export const GET_BUSINESS_TYPES = 'GET_BUSINESS_TYPES'
export const GET_ENTERPRISE_TYPES = 'GET_ENTERPRISE_TYPES'
export const GET_IS_CONFIRMS = 'GET_IS_CONFIRMS'
export const GET_IS_DELETES = 'GET_IS_DELETES'
export const GET_LEGAL_TYPES = 'GET_LEGAL_TYPES'
export const GET_NODE_TYPES = 'GET_NODE_TYPES'
export const GET_PROPERTIES = 'GET_PROPERTIES'
export const GET_TOKEN = 'GET_TOKEN'
export const GET_LOGIN_USER = 'GET_LOGIN_USER'
export const FIND_REGION_PARENT_LIST = 'FIND_REGION_PARENT_LIST'
export const FIND_CHANNEL_CONTENT_TYPE_ENUMS = 'FIND_CHANNEL_CONTENT_TYPE_ENUMS'
export const FIND_CHANNEL_STATE_ENUMS = 'FIND_CHANNEL_STATE_ENUMS'
export const FIND_CHANNEL_TYPE_ENUMS = 'FIND_CHANNEL_TYPE_ENUMS'
export const FIND_IS_MENU_ENUMS = 'FIND_IS_MENU_ENUMS'
export const FIND_TEMPLATE_TYPE_ENUMS = 'FIND_TEMPLATE_TYPE_ENUMS'
export const SET_DIALOG_FORM_VISIBLE = 'SET_DIALOG_FORM_VISIBLE'
// 平台首页 经营主体分布统计
export const GET_ENTERPRISE_COUNT_DATA = 'GET_ENTERPRISE_COUNT_DATA'
// 平台首页 设备运行情况
export const GET_EQUIPMENT_RUN_STATUS_DATA = 'GET_EQUIPMENT_RUN_STATUS_DATA'
// 平台首页 上季度追溯数据分析
export const GET_LAST_QUARTER_TRACE_DATA_ANALYSIS_DATA = 'GET_LAST_QUARTER_TRACE_DATA_ANALYSIS_DATA'
// 平台首页 工作考核分析
export const GET_WORK_EXAMINE_ANALYSIS_DATA = 'GET_WORK_EXAMINE_ANALYSIS_DATA'
// 平台首页 今日提示
export const GET_TODAY_STAT_DATA = 'GET_TODAY_STAT_DATA'
// 平台首页 各流通节点考核情况分析
export const GET_NODE_TYPE_EXAMINE_ANALYSIS_DATA = 'GET_NODE_TYPE_EXAMINE_ANALYSIS_DATA'
