export const GET_MENU_LIST = 'GET_MENU_LIST'
export const GET_CREDIT_RANK_TABLE_DATA = 'GET_CREDIT_RANK_TABLE_DATA'
export const GET_SUPERVISE_SYSTEM_TABLE_DATA = 'GET_SUPERVISE_SYSTEM_TABLE_DATA'
export const GET_SUPERVISE_TOP_TABLE_DATA = 'GET_SUPERVISE_TOP_TABLE_DATA'
export const GET_INDEX_BASE_TABLE_DATA = 'GET_INDEX_BASE_TABLE_DATA'
export const GET_EARLY_WARNING_TABLE_DATA = 'GET_EARLY_WARNING_TABLE_DATA'
export const GET_QUESTION_REPORT_TABLE_DATA = 'GET_QUESTION_REPORT_TABLE_DATA'
export const GET_USER_TABLE_DATA = 'GET_USER_TABLE_DATA'
export const GET_CREDIT_ARCHIVES_TABLE_DATA = 'GET_CREDIT_ARCHIVES_TABLE_DATA'
export const GET_CORPORATE_BLACKLIST_TABLE_DATA = 'GET_CORPORATE_BLACKLIST_TABLE_DATA'
export const GET_PERSONAL_BLACKLIST_TABLE_DATA = 'GET_PERSONAL_BLACKLIST_TABLE_DATA'
export const GET_INTEGRITY_RECORD_TABLE_DATA = 'GET_INTEGRITY_RECORD_TABLE_DATA'
//  监管辅助系统 --> 视频集中管理 --> 监控视频 --> 监控视频画面
export const GET_VIDEO_LIST_DATA = 'GET_VIDEO_LIST_DATA'
//  监管辅助系统 --> 视频集中管理 --> 监控视频 --> 监控视频信息列表
export const GET_MONITOR_VIDEO_TABLE_DATA = 'GET_MONITOR_VIDEO_TABLE_DATA'
//  监管辅助系统 --> 视频集中管理 --> 监控记录
export const GET_VIDEO_RECORD_TABLE_DATA = 'GET_VIDEO_RECORD_TABLE_DATA'
export const GET_QUESTION_COUNT_TABLE_DATA = 'GET_QUESTION_COUNT_TABLE_DATA'
export const GET_EMERGENCY_PLAN_TABLE_DATA = 'GET_EMERGENCY_PLAN_TABLE_DATA'
export const GET_EMERGENCY_RECORD_TABLE_DATA = 'GET_EMERGENCY_RECORD_TABLE_DATA'
export const GET_EMERGENCY_HANDLE_TABLE_DATA = 'GET_EMERGENCY_HANDLE_TABLE_DATA'
export const SELECTED_GENERATE_REPORT_USER_LIST = 'SELECTED_GENERATE_REPORT_USER_LIST'
// 审核枚举
export const GET_PROBLEMREPORT_TYPES = 'GET_GET_PROBLEMREPORT_TYPES'
// 设备管理 设备管理
export const GET_EQUIPMENT_TABLE_DATA = 'GET_EQUIPMENT_TABLE_DATA'
// 设备管理 设备调整管理
export const GET_EQUIPMENT_ADJUST_TABLE_DATA = 'GET_EQUIPMENT_ADJUST_TABLE_DATA'
// 设备管理 设备调整管理 用于选择的设备发放列表
export const GET_EQUIPMENT_SELECT_TABLE_DATA = 'GET_EQUIPMENT_SELECT_TABLE_DATA'
// 设备管理 设备调整管理 选择的发放的设备列表
export const GET_EQUIPMENT_SELECT_LIST_DATA = 'GET_EQUIPMENT_SELECT_LIST_DATA'
// 设备管理 设备监控管理
export const GET_EQUIPMENT_MONITOR_TABLE_DATA = 'GET_EQUIPMENT_MONITOR_TABLE_DATA'
// 设备管理 设备维护管理
export const GET_EQUIPMENT_REPAIR_TABLE_DATA = 'GET_EQUIPMENT_REPAIR_TABLE_DATA'
// 设备管理 设备维护管理 用于选择的送还维护的设备列表
export const GET_EQUIPMENT_RETURN_SELECT_TABLE_DATA = 'GET_EQUIPMENT_RETURN_SELECT_TABLE_DATA'
// 设备管理 设备维护管理 选择的送还维护的设备列表
export const GET_EQUIPMENT_RETURN_SELECT_LIST_DATA = 'GET_EQUIPMENT_RETURN_SELECT_LIST_DATA'
// 设备管理 设备库存管理 完好设备库存
export const GET_NORMAL_EQUIPMENT_STORAGE_TABLE_DATA = 'GET_NORMAL_EQUIPMENT_STORAGE_TABLE_DATA'
// 设备管理 设备库存管理 损坏设备库存
export const GET_ABNORMAL_EQUIPMENT_STORAGE_TABLE_DATA = 'GET_ABNORMAL_EQUIPMENT_STORAGE_TABLE_DATA'
//企业诚信类型 枚举
export const GET_HONESTY_TYPE_ENUM_DATE = 'GET_HONESTY_TYPE_ENUM_DATE'
//增加企业诚信记录
export const GET_ADD_CREDIT_ARCHIVES = 'GET_ADD_CREDIT_ARCHIVES'
//企业信息枚举
export const GET_ENTERPRISE_INFO_ENUM_DATE = 'GET_ENTERPRISE_INFO_ENUM_DATE'
//考核指标类型管理
export const GET_SHOW_ASSESS_TYPE_LIST = 'GET_SHOW_ASSESS_TYPE_LIST'
//单项考核信息
//总工作考核管理
export const GET_TOTAL_EXAMINE = 'GET_TOTAL_EXAMINE'
//单项考核信息
export const SINGLE_EXAMINE = 'SINGLE_EXAMINE'
//单项考核信息 --> 工作考核按企业、流通节点类型、指标排名
export const GET_SINGLE_EXAMINE_NODE_TABLE_DATA = 'GET_SINGLE_EXAMINE_NODE_TABLE_DATA'
//单项考核信息 --> 按流通节点排名 --> 按企业排名 --> 查看
export const GET_SHOW_INDEX = 'GET_SHOW_INDEX'
//单项考核信息 --> 按流通节点排名 --> 按流通节点类型排名 -->  查看
export const GET_NODE_TYPE_SHOW_INDEX = 'GET_NODE_TYPE_SHOW_INDEX'
//单项考核信息 --> 按流通节点排名 --> 查看
export const SET_SHOWINDEX_DATA = 'SET_SHOWINDEX_DATA'
export const GET_EXAMINE_TYPE_ENUM = 'GET_EXAMINE_TYPE_ENUM'
// 设备管理 设备库存管理 完好设备库存 设备类别下设备型号库存中 设备详情
export const FIND_NORMAL_EQUIPMENT_MODEL_VIEW_DETAIL = 'FIND_NORMAL_EQUIPMENT_MODEL_VIEW_DETAIL'
// 设备管理 设备库存管理 损坏设备库存 设备类别下设备型号库存中 设备详情
export const FIND_ABNORMAL_EQUIPMENT_MODEL_VIEW_DETAIL = 'FIND_ABNORMAL_EQUIPMENT_MODEL_VIEW_DETAIL'
//跨城市应急事件
export const GET_EMERGENCY_CITY_HANDLE_TABLE_DATA = 'GET_EMERGENCY_CITY_HANDLE_TABLE_DATA'
export const GET_EMERGENCY_CITY_RECORD_TABLE_DATA = 'GET_EMERGENCY_CITY_RECORD_TABLE_DATA'
export const SELECTED_CITY_GENERATE_REPORT_USER_LIST = 'SELECTED_CITY_GENERATE_REPORT_USER_LIST'
//单项考核信息 --> 时间参数页面传值
export const SET_SINGLE_EXAMINE_ENTERPRISE_ET_DATE = 'SET_SINGLE_EXAMINE_ENTERPRISE_ET_DATE'
//单项考核信息 --> 按考核指标排名
export const GET_SINGLE_EXAMINE_INDEX = 'GET_SINGLE_EXAMINE_INDEX'
export const GET_SENDUSERLIST = 'GET_SENDUSERLIST'
